# Generated by Django 4.1.7 on 2023-03-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_color_size_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='brands',
            field=models.ManyToManyField(related_name='product_brand', to='shop.brand'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='colors',
            field=models.ManyToManyField(related_name='product_colors', to='shop.color'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='sizes',
            field=models.ManyToManyField(related_name='product_sizes', to='shop.size'),
        ),
    ]
