# Generated by Django 4.1.7 on 2023-03-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productattribute_brands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='brand_color',
        ),
        migrations.RemoveField(
            model_name='color',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='color',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='colors',
        ),
        migrations.AddField(
            model_name='color',
            name='color',
            field=models.CharField(default='white', max_length=30, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='brand_color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='brand color'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='primary_color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='primary color'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='secondary color'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='brands',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_brand', to='shop.brand'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_sizes', to='shop.size'),
        ),
    ]
