# Generated by Django 4.1.7 on 2023-03-06 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_color_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diversity', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='stock'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='diversities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_diversity', to='shop.diversity'),
        ),
    ]
