# Generated by Django 4.1.7 on 2023-03-07 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_diversity_remove_product_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='shop.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='product_colors'),
        ),
        migrations.AddField(
            model_name='product',
            name='diversities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_diversity', to='shop.diversity'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='shop.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='sleeves',
            field=models.BooleanField(blank=True, null=True, verbose_name='has sleeves'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='stock'),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
