# Generated by Django 4.1.7 on 2023-03-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_available_product_brands_product_colors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotton', models.PositiveIntegerField(default=0, verbose_name='cotton percent')),
                ('linen', models.PositiveIntegerField(default=0, verbose_name='linen percent')),
                ('hemp', models.PositiveIntegerField(default=0, verbose_name='hemp percent')),
                ('polyester', models.PositiveIntegerField(default=0, verbose_name='polyester percent')),
                ('nylon', models.PositiveIntegerField(default=0, verbose_name='nylon percent')),
                ('wool', models.PositiveIntegerField(default=0, verbose_name='wool percent')),
                ('silk', models.PositiveIntegerField(default=0, verbose_name='silk percent')),
            ],
        ),
    ]
