# Generated by Django 4.1.7 on 2023-03-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compositions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_composition', to='shop.composition'),
        ),
    ]
