# Generated by Django 4.1.7 on 2023-03-08 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_compositions_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'created'], 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
    ]
