# Generated by Django 4.1.7 on 2023-03-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.CharField(default='unknown', max_length=120, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(default='unknown@hunknown.com', max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='first_name',
            field=models.CharField(default='Joe', max_length=120, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_name',
            field=models.CharField(default='Doe', max_length=120, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone',
            field=models.PositiveIntegerField(default=0, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='postal',
            field=models.CharField(default='0000', max_length=120, verbose_name='postal code'),
        ),
    ]
